[package]
name = "youtube-url-unwrap"
version = "0.1.0"
authors = ["m.zhuravlev <maks723@yandex.ru>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.70"
wasm-bindgen-futures = "0.4.20"
serde = { version = "1.0.80", features = ["derive"] }
Boa = "0.10.0"
reqwest = { version = "0.11", features = ["blocking", "json"] }
web-sys = { version = "0.3.47", features = ["console", "Request", "RequestInit", "RequestMode", "Response"] }

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
